"""
Phase 6: idempotent git post-commit hook install/uninstall.

Mirrors the marker-wrapped injection pattern from cli/init.py so it composes with
an existing post-commit hook instead of clobbering it. The hook calls
`python -m hive.cli.capture <sha>` on every commit — synchronous, no daemon, no new
dependency. Failures in capture must never block a commit, so the injected block
swallows errors.

Usage:
    python -m hive.cli.hook install   [--repo PATH]
    python -m hive.cli.hook uninstall [--repo PATH]
    python -m hive.cli.hook status    [--repo PATH]
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

BEGIN = "# >>> HIVE:BEGIN (auto-generated by `hive hook install` — edit outside these markers) >>>"
END = "# <<< HIVE:END <<<"

# The injected hook body. Best-effort: never fail a commit because capture broke.
HOOK_BODY = """{begin}
# Capture the just-made commit into Hive memory (decisions + snapshot only).
HIVE_SHA="$(git rev-parse HEAD)"
python -m hive.cli.capture "$HIVE_SHA" >/dev/null 2>&1 || true
{end}""".format(begin=BEGIN, end=END)

SHEBANG = "#!/bin/sh\n"


def _hook_path(repo: str | None) -> Path:
    cmd = ["git"]
    if repo:
        cmd += ["-C", repo]
    cmd += ["rev-parse", "--git-path", "hooks/post-commit"]
    out = subprocess.run(cmd, capture_output=True, text=True)
    if out.returncode != 0:
        raise RuntimeError(out.stderr.strip() or "not a git repository")
    p = Path(out.stdout.strip())
    if not p.is_absolute() and repo:
        p = Path(repo) / p
    return p


def _render(existing: str) -> str:
    """Insert or replace the marker-wrapped block. Pure (testable)."""
    if BEGIN in existing and END in existing:
        pre = existing.split(BEGIN, 1)[0]
        post = existing.split(END, 1)[1]
        return (pre + HOOK_BODY + post).rstrip() + "\n"
    if existing.strip() == "":
        return SHEBANG + HOOK_BODY + "\n"
    base = existing if existing.startswith("#!") else SHEBANG + existing
    return base.rstrip() + "\n\n" + HOOK_BODY + "\n"


def _render_uninstall(existing: str) -> str:
    """Remove only Hive's block; leave any other hook content intact."""
    if BEGIN not in existing or END not in existing:
        return existing
    pre = existing.split(BEGIN, 1)[0]
    post = existing.split(END, 1)[1]
    merged = (pre.rstrip() + "\n" + post.lstrip()).strip()
    if merged in ("", SHEBANG.strip()):
        return ""   # nothing left but a shebang → signal full removal
    return (merged if merged.startswith("#!") else SHEBANG + merged).rstrip() + "\n"


def install(repo: str | None = None, dry_run: bool = False) -> tuple[str, str]:
    path = _hook_path(repo)
    existing = path.read_text(encoding="utf-8") if path.exists() else ""
    new = _render(existing)
    if new == existing:
        return (str(path), "unchanged")
    if not dry_run:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(new, encoding="utf-8")
        try:
            path.chmod(0o755)
        except Exception:
            pass
    return (str(path), "would-write" if dry_run else "installed")


def uninstall(repo: str | None = None) -> tuple[str, str]:
    path = _hook_path(repo)
    if not path.exists():
        return (str(path), "absent")
    existing = path.read_text(encoding="utf-8")
    new = _render_uninstall(existing)
    if new == existing:
        return (str(path), "unchanged")
    if new == "":
        path.unlink()
        return (str(path), "removed")
    path.write_text(new, encoding="utf-8")
    return (str(path), "cleaned")


def status(repo: str | None = None) -> tuple[str, str]:
    path = _hook_path(repo)
    if not path.exists():
        return (str(path), "absent")
    txt = path.read_text(encoding="utf-8")
    return (str(path), "installed" if BEGIN in txt else "present-no-hive")


def main() -> None:
    args = sys.argv[1:]
    repo = None
    rest = []
    i = 0
    while i < len(args):
        if args[i] == "--repo" and i + 1 < len(args):
            repo = args[i + 1]; i += 2
        else:
            rest.append(args[i]); i += 1

    cmd = rest[0] if rest else "status"
    if cmd == "install":
        path, st = install(repo)
    elif cmd == "uninstall":
        path, st = uninstall(repo)
    else:
        path, st = status(repo)
    print(f"  [{st:<12}] {path}")


if __name__ == "__main__":
    main()
