"""
Phase 3: idempotent global-config init.

Makes Hive discoverable to whatever agent runs next by injecting a usage block
into global agent rule files (~/.claude/CLAUDE.md, etc.). The block is wrapped in
HIVE:BEGIN / HIVE:END markers so re-running `hive init` REPLACES it in place
rather than appending a duplicate — and is a no-op when nothing changed.

Usage:
    python -m hive.cli.init            # write the block to discovered targets
    python -m hive.cli.init --dry-run  # show what would change, write nothing
"""

from __future__ import annotations

import sys
from pathlib import Path

BEGIN = "<!-- HIVE:BEGIN (auto-generated by `hive init` — edit outside these markers) -->"
END = "<!-- HIVE:END -->"

HIVE_BLOCK = """## Hive Mind — persistent cross-agent memory

This project uses Hive Mind. Before re-deriving context from source, read memory;
after a decision, write it back so the next agent inherits it.

- Read context:    `from hive import read_memory; ctx = read_memory(project, query="...")`
- Record decision: `from hive import write_memory; write_memory("decision", project, {"what": ..., "why": ...})`
- Record dead end: `write_memory("dead_end", project, {"what_tried": ..., "why_failed": ..., "chosen_decision_id": ...})`
- Provenance:      `from hive import get_provenance; get_provenance(decision_id)`
"""


def _default_targets() -> list[Path]:
    """
    Global rule files to inject into. ~/.claude/CLAUDE.md is always included
    (its parent is created if missing); other vendor targets are only touched
    when their parent dir already exists, so we never create dirs for tools the
    user doesn't have installed.
    """
    home = Path.home()
    always = [home / ".claude" / "CLAUDE.md"]
    optional = [
        home / ".cursorrules",
        home / ".codeium" / "windsurf" / "memories" / "global_rules.md",
    ]
    return always + [p for p in optional if p.parent.exists()]


def _render(existing: str, block: str) -> str:
    """Insert or replace the marker-wrapped block. Pure function (testable)."""
    wrapped = f"{BEGIN}\n{block.rstrip()}\n{END}"
    if BEGIN in existing and END in existing:
        pre = existing.split(BEGIN, 1)[0]
        post = existing.split(END, 1)[1]
        return pre + wrapped + post
    if existing.strip() == "":
        return wrapped + "\n"
    return existing.rstrip() + "\n\n" + wrapped + "\n"


def init_global_config(targets: list[Path] | None = None, dry_run: bool = False) -> list[tuple[str, str]]:
    """
    Inject the Hive block into each target idempotently. Returns a list of
    (path, status) where status ∈ {'written','unchanged','would-write'}.
    """
    targets = targets if targets is not None else _default_targets()
    results: list[tuple[str, str]] = []
    for path in targets:
        path = Path(path)
        existing = path.read_text(encoding="utf-8") if path.exists() else ""
        new = _render(existing, HIVE_BLOCK)
        if new == existing:
            results.append((str(path), "unchanged"))
            continue
        if not dry_run:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(new, encoding="utf-8")
        results.append((str(path), "would-write" if dry_run else "written"))
    return results


def main() -> None:
    dry = "--dry-run" in sys.argv[1:]
    for path, status in init_global_config(dry_run=dry):
        print(f"  [{status:<11}] {path}")
    if dry:
        print("\n  (dry run — no files written)")


if __name__ == "__main__":
    main()
